# Configuração do Cloudflare Tunnel para CCCP
# Arquivo: cloudflare/config.yml

tunnel: cccp-tunnel
credentials-file: /etc/cloudflared/credentials.json

# Configurações de entrada (ingress rules)
ingress:
  # Rota para API - api.casadeprovision.es -> backend:4000
  - hostname: api.casadeprovision.es
    service: http://backend:4000
    originRequest:
      httpHostHeader: api.casadeprovision.es
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      keepAliveConnections: 10
      keepAliveTimeout: 90s

  # Rota principal com www - www.casadeprovision.es -> frontend:80
  - hostname: www.casadeprovision.es
    service: http://frontend:80
    originRequest:
      httpHostHeader: www.casadeprovision.es
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      keepAliveConnections: 10
      keepAliveTimeout: 90s

  # Rota principal - casadeprovision.es -> frontend:80
  - hostname: casadeprovision.es
    service: http://frontend:80
    originRequest:
      httpHostHeader: casadeprovision.es
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      keepAliveConnections: 10
      keepAliveTimeout: 90s

  # Rota de fallback - deve ser sempre a última
  - service: http_status:404

# Configurações do daemon
warp-routing:
  enabled: false

# Métricas e monitoramento
metrics: 0.0.0.0:8080

# Logs
loglevel: info

# Configurações de rede
no-autoupdate: true
protocol: auto

# Configurações de retry
retries: 5
grace-period: 30s